// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: addressiq/v1/common.proto

/* eslint-disable */

export const protobufPackage = "addressiq.v1";

export enum EnvironmentBucket {
  ENVIRONMENT_BUCKET_UNSPECIFIED = 0,
  DENSE_URBAN = 1,
  URBAN = 2,
  SUBURBAN = 3,
  RURAL = 4,
  SPARSE_RURAL = 5,
  UNRECOGNIZED = -1,
}

/**
 * The single closed set of error codes every SDK must carry. New entries
 * require a spec change in docs/sdk-contract.md §3.
 */
export enum ErrorCode {
  ERROR_CODE_UNSPECIFIED = 0,
  SDK_NOT_INITIALIZED = 1,
  INVALID_CONFIG = 2,
  INVALID_USER = 3,
  NO_ACTIVE_SESSION = 4,
  IDEMPOTENCY_KEY_REQUIRED = 5,
  IDEMPOTENCY_KEY_INVALID = 6,
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD = 7,
  PROVIDER_NOT_FOUND = 8,
  PROVIDER_DISABLED_FOR_ORG = 9,
  PROVIDER_TYPE_MISMATCH = 10,
  PRODUCT_NOT_SUBSCRIBED = 11,
  PHOTO_HASH_REUSED = 12,
  VERIFICATION_ILLEGAL_TRANSITION = 13,
  BROWSER_VERIFICATION_NOT_SUPPORTED = 14,
  UNRECOGNIZED = -1,
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
  country: string;
  status: string;
}

export interface AppUser {
  id: string;
  organizationId: string;
  appId: string;
  appUserId: string;
  /**
   * PII fields are NOT carried on the wire — only their hashes for
   * matching/dedup. Mobile SDKs encrypt locally before transit.
   */
  phoneHash: string;
  emailHash: string;
  /** APP_USER_ID | PHONE | EMAIL | GENERATED */
  identitySource: string;
}

export interface GeoPoint {
  lat: number;
  lon: number;
}

export interface SdkError {
  code: ErrorCode;
  message: string;
  docsUrl: string;
}
