// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: addressiq/v1/sdk.proto

/* eslint-disable */

export const protobufPackage = "addressiq.v1";

export enum LifecycleState {
  LIFECYCLE_STATE_UNSPECIFIED = 0,
  UNINITIALIZED = 1,
  IDLE = 2,
  COLLECTING = 3,
  PAUSED = 4,
  TERMINATED = 5,
  UNRECOGNIZED = -1,
}

export enum PermissionStatus {
  PERMISSION_STATUS_UNSPECIFIED = 0,
  GRANTED = 1,
  DENIED = 2,
  NOT_DETERMINED = 3,
  BLOCKED = 4,
  PERMISSION_UNAVAILABLE = 5,
  UNRECOGNIZED = -1,
}

export interface SdkUser {
  appUserId: string;
  /** encrypted at rest on device — wire = plaintext under HTTPS */
  phone: string;
  email: string;
  firstName: string;
  lastName: string;
}

export interface VerificationLifecycleState {
  state: LifecycleState;
  appUserId: string;
  verificationId: string;
  locationCode: string;
  pausedForMs: number;
}

export interface PermissionState {
  foregroundLocation: PermissionStatus;
  backgroundLocation: PermissionStatus;
  notifications: PermissionStatus;
}

export interface InvalidateSessionRequest {
  appUserId: string;
  verificationCode: string;
}

export interface InvalidateSessionResponse {
  revoked: boolean;
}
