// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: addressiq/v1/telemetry.proto

/* eslint-disable */
import type { GeoPoint } from "./common";

export const protobufPackage = "addressiq.v1";

export enum TransitEventType {
  TRANSIT_EVENT_TYPE_UNSPECIFIED = 0,
  GEOFENCE_ENTER = 1,
  GEOFENCE_EXIT = 2,
  DWELL = 3,
  APP_OPEN = 4,
  BACKGROUND_CHECK = 5,
  ACTIVITY_UPDATE = 6,
  UNRECOGNIZED = -1,
}

export enum ActivityType {
  ACTIVITY_TYPE_UNSPECIFIED = 0,
  STILL = 1,
  WALKING = 2,
  RUNNING = 3,
  IN_VEHICLE = 4,
  ACTIVITY_UNKNOWN = 5,
  UNRECOGNIZED = -1,
}

export enum DeviceOs {
  DEVICE_OS_UNSPECIFIED = 0,
  IOS = 1,
  ANDROID = 2,
  UNRECOGNIZED = -1,
}

export enum IntegrityVerdict {
  INTEGRITY_VERDICT_UNSPECIFIED = 0,
  MEETS_BASIC = 1,
  MEETS_DEVICE = 2,
  MEETS_STRONG = 3,
  UNAVAILABLE = 4,
  UNRECOGNIZED = -1,
}

export interface SecurityEnvelope {
  deviceFingerprintHash: string;
  attestationToken: string;
  integrityVerdict: IntegrityVerdict;
}

export interface TransitEvent {
  /** UUID v4 generated client-side. Server dedups via 24h Redis SETNX. */
  eventId: string;
  locationId: string;
  eventType: TransitEventType;
  /** optional (events without GPS are valid) */
  position?: GeoPoint | undefined;
  accuracyM: number;
  distanceFromPinM: number;
  activityType: ActivityType;
  /** 0..100 */
  activityConfidence: number;
  /** 0..100 */
  batteryLevel: number;
  isCharging: boolean;
  deviceOs: DeviceOs;
  sdkVersion: string;
  deviceTimestamp?: Date | undefined;
  security?: SecurityEnvelope | undefined;
}

export interface TransitEventBatch {
  events: TransitEvent[];
}

export interface TransitEventBatchAck {
  accepted: number;
  deduplicated: number;
}
