// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: addressiq/v1/verification.proto

/* eslint-disable */
import type { EnvironmentBucket, GeoPoint } from "./common";

export const protobufPackage = "addressiq.v1";

export enum VerificationType {
  VERIFICATION_TYPE_UNSPECIFIED = 0,
  DIGITAL = 1,
  PHYSICAL = 2,
  COMBINED = 3,
  UNRECOGNIZED = -1,
}

export enum VerificationStatus {
  VERIFICATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  ASSIGNED = 2,
  IN_PROGRESS = 3,
  VERIFIED = 4,
  NOT_AT_ADDRESS = 5,
  STATUS_UNKNOWN = 6,
  FAILED = 7,
  EXPIRED = 8,
  CANCELLED = 9,
  UNDER_REVIEW = 10,
  UNRECOGNIZED = -1,
}

export enum ReviewState {
  REVIEW_STATE_UNSPECIFIED = 0,
  NONE = 1,
  FLAGGED = 2,
  MANUAL_REVIEW = 3,
  ESCALATED = 4,
  RESOLVED = 5,
  UNRECOGNIZED = -1,
}

export interface Verification {
  id: string;
  verificationCode: string;
  organizationId: string;
  appId: string;
  branchId: string;
  appUserId: string;
  locationId: string;
  type: VerificationType;
  /** slug */
  provider: string;
  providerReferenceId: string;
  status: VerificationStatus;
  reviewState: ReviewState;
  confidenceScore: number;
  windowEndsAt?: Date | undefined;
  resolvedAt?: Date | undefined;
}

export interface Location {
  id: string;
  locationCode: string;
  position?: GeoPoint | undefined;
  geofenceRadiusM: number;
  /** Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences. */
  adaptiveGeofenceRadiusMeters: number;
  environment: EnvironmentBucket;
}
